---
- name: 'Install Apache'
  apt:
    name: apache2
  become: true

- name: 'Enable Apache modules'
  command: "{{ item }}"
  with_items:
    - a2enmod perl
    - a2enmod deflate
    - a2enmod filter
    - a2enmod headers
    - a2enmod ssl 
    - a2enmod rewrite
  become: true

- name: 'Create site config for Apache'
  file:
    src: /opt/otrs/scripts/apache2-httpd.include.conf
    dest: /etc/apache2/sites-available/zzz_otrs.conf
    state: link
  become: true

- name: Copy Apache SSL Config
  copy:
    src: default-ssl.conf
    dest: /etc/apache2/sites-enabled/default-ssl.conf
  become: true

- name: Copy Apache Default Config
  copy:
    src: 000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  become: true

- name: 'Enable apache site'
  command: a2ensite zzz_otrs.conf
  become: true
  notify: restart apache
